apiVersion: v1
kind: ServiceAccount
metadata:
  name: hammerspace-csi-operator
  namespace: hammerspace-csi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hammerspace-csi-operator
rules:
- apiGroups:
  - storage.hammerspace.com
  resources:
  - hammerspacecsidrivers
  verbs:
  - get
  - update
  - patch
  resourceNames:
  - cluster
- apiGroups:
  - storage.hammerspace.com
  resources:
  - hammerspacecsidrivers/status
  verbs:
  - get
  - update
  - patch
  resourceNames:
  - cluster
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  resourceNames:
  - hammerspace-csi
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - get
  - update
  - patch
  - delete
  resourceNames:
  - com.hammerspace.csi
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - update
  - patch
  - delete
  resourceNames:
  - hammerspace-csi-node
  - hammerspace-csi-provisioner
  - hammerspace-csi-provisioner-snapshot-content-status
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - update
  - patch
  - delete
  resourceNames:
  - hammerspace-csi-node
  - hammerspace-csi-provisioner
  - hammerspace-csi-provisioner-snapshot-content-status-binding
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - get
  - update
  - patch
  - delete
  resourceNames:
  - hammerspace-csi
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - persistentvolumes
  verbs:
  - get
  - patch
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - get
  - patch
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - create
  - update
  - delete
  - get
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  - volumeattachments/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - csistoragecapacities
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ''
  resources:
  - namespaces
  - events
  verbs:
  - get
  - list
  - create
- apiGroups:
  - ''
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  - volumesnapshotcontents/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hammerspace-csi-operator
  namespace: hammerspace-csi
rules:
- apiGroups:
  - ''
  resources:
  - services
  - serviceaccounts
  - configmaps
  verbs: &id001
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  verbs: *id001
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs: *id001
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hammerspace-csi-operator
subjects:
- kind: ServiceAccount
  name: hammerspace-csi-operator
  namespace: hammerspace-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hammerspace-csi-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hammerspace-csi-operator
  namespace: hammerspace-csi
subjects:
- kind: ServiceAccount
  name: hammerspace-csi-operator
  namespace: hammerspace-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hammerspace-csi-operator
