package manifests

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/util/yaml"
	syaml "sigs.k8s.io/yaml"
)

// ImageDefaults derives development image configuration from generated operands.
func ImageDefaults(operands []byte) (map[string]string, error) {
	var objects []map[string]interface{}
	if err := json.Unmarshal(operands, &objects); err != nil {
		return nil, err
	}
	images := map[string]string{}
	for _, object := range objects {
		if object["kind"] != "StatefulSet" && object["kind"] != "DaemonSet" {
			continue
		}
		containers, _, err := unstructured.NestedSlice(object, "spec", "template", "spec", "containers")
		if err != nil {
			return nil, err
		}
		for _, item := range containers {
			container, ok := item.(map[string]interface{})
			if !ok {
				return nil, fmt.Errorf("invalid operand container")
			}
			name, _ := container["name"].(string)
			key, ok := ContainerImageKey(name)
			if !ok {
				return nil, fmt.Errorf("no release image mapping for container %q", name)
			}
			image, _ := container["image"].(string)
			if image == "" || (images[key] != "" && images[key] != image) {
				return nil, fmt.Errorf("missing or conflicting image for %s", key)
			}
			images[key] = image
		}
	}
	return images, nil
}

func ContainerImageKey(name string) (string, bool) {
	key, ok := map[string]string{
		"hs-csi-plugin-controller": "driver", "hs-csi-plugin-node": "driver",
		"csi-provisioner": "provisioner", "csi-attacher": "attacher",
		"csi-snapshotter": "snapshotter", "csi-resizer": "resizer",
		"driver-registrar": "registrar", "liveness-probe": "livenessprobe",
	}[name]
	return key, ok
}

// ManagerImages updates only image environment values; all other manager
// settings are preserved. The returned YAML has deterministic formatting.
func ManagerImages(source io.Reader, images map[string]string) ([]byte, error) {
	decoder := yaml.NewYAMLOrJSONDecoder(source, 4096)
	var result bytes.Buffer
	result.WriteString("# RELATED_IMAGE_* defaults are generated by make generate from the canonical plugin.yaml.\n")
	found := false
	documents := 0
	for {
		var object map[string]interface{}
		if err := decoder.Decode(&object); err == io.EOF {
			break
		} else if err != nil {
			return nil, err
		}
		if len(object) == 0 {
			continue
		}
		if object["kind"] == "Deployment" {
			containers, _, err := unstructured.NestedSlice(object, "spec", "template", "spec", "containers")
			if err != nil {
				return nil, err
			}
			for _, item := range containers {
				container := item.(map[string]interface{})
				if container["name"] != "manager" {
					continue
				}
				found = true
				if err := setManagerImages(container, images); err != nil {
					return nil, err
				}
			}
			unstructured.SetNestedSlice(object, containers, "spec", "template", "spec", "containers")
		}
		data, err := syaml.Marshal(object)
		if err != nil {
			return nil, err
		}
		if documents > 0 {
			result.WriteString("---\n")
		}
		result.Write(data)
		documents++
	}
	if !found {
		return nil, fmt.Errorf("manager Deployment is missing")
	}
	return result.Bytes(), nil
}

func setManagerImages(container map[string]interface{}, images map[string]string) error {
	env, _, err := unstructured.NestedSlice(container, "env")
	if err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, item := range env {
		variable, ok := item.(map[string]interface{})
		if !ok {
			return fmt.Errorf("invalid manager environment variable")
		}
		name, _ := variable["name"].(string)
		if !strings.HasPrefix(name, "RELATED_IMAGE_") {
			continue
		}
		key := strings.ToLower(strings.TrimPrefix(name, "RELATED_IMAGE_"))
		if images[key] == "" || seen[key] {
			return fmt.Errorf("unknown or duplicate manager image %s", key)
		}
		variable["value"] = images[key]
		delete(variable, "valueFrom")
		seen[key] = true
	}
	for key := range images {
		if !seen[key] {
			return fmt.Errorf("manager environment is missing image %s", key)
		}
	}
	return unstructured.SetNestedSlice(container, env, "env")
}
