apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hammerspace-block-example
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  storageClassName: hammerspace-block
  resources:
    requests:
      storage: 1Gi
